# Generated by Django 5.0.2 on 2024-02-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_desg'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_contact', models.CharField(max_length=50)),
                ('emp_email', models.CharField(max_length=50)),
                ('dept_name', models.CharField(max_length=50)),
                ('desg_name', models.CharField(max_length=50)),
                ('emp_bs', models.CharField(max_length=50)),
            ],
        ),
    ]
