# Generated by Django 5.0.2 on 2024-02-15 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tbl_emp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_emp',
        ),
    ]
