# Generated by Django 5.0.2 on 2024-02-15 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_delete_tbl_emp'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_contact', models.CharField(max_length=50)),
                ('emp_email', models.CharField(max_length=50)),
                ('emp_bs', models.CharField(max_length=50)),
                ('deptid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_dept')),
                ('desgid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_desg')),
            ],
        ),
    ]
