# Generated by Django 5.0.2 on 2024-02-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_emp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_emp',
            old_name='deptid',
            new_name='dept_name',
        ),
        migrations.RenameField(
            model_name='tbl_emp',
            old_name='desgid',
            new_name='desg_name',
        ),
    ]
