# Generated by Django 5.0.2 on 2024-02-15 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_rename_deptid_tbl_emp_dept_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('course_duration', models.CharField(max_length=50)),
                ('semno', models.CharField(max_length=50)),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_dept')),
            ],
        ),
    ]
