# Generated by Django 5.0.2 on 2024-02-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_name', models.CharField(max_length=50)),
            ],
        ),
    ]
