# Generated by Django 5.0.2 on 2024-02-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_syllabus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_syllabus',
        ),
    ]
