# Generated by Django 5.0.2 on 2024-02-18 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_delete_tbl_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_name', models.CharField(max_length=50)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_course')),
                ('semester_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_semester')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject')),
            ],
        ),
    ]
