# Generated by Django 5.0.2 on 2024-02-26 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_tbl_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
    ]
