# Generated by Django 5.0.2 on 2024-02-26 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0022_delete_tbl_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_desc', models.CharField(max_length=50)),
                ('product_photo', models.FileField(upload_to='Assets/productphoto/')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_product')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subcategory')),
            ],
        ),
    ]
