# Generated by Django 5.0.2 on 2024-03-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0029_tbl_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='subcateg_name',
        ),
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
        migrations.DeleteModel(
            name='tbl_product',
        ),
    ]
