# Generated by Django 5.0.2 on 2024-03-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0038_tbl_productcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_productcategory',
        ),
    ]
