# Generated by Django 5.0.2 on 2024-03-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0039_delete_tbl_productcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_productcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcategory_name', models.CharField(max_length=50)),
            ],
        ),
    ]
