# Generated by Django 5.0.2 on 2024-03-24 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0040_tbl_productcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='category_name',
        ),
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
        migrations.DeleteModel(
            name='tbl_product',
        ),
    ]
