# Generated by Django 5.0.2 on 2024-03-25 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0042_tbl_product_tbl_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='tbl_gallery',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='tbl_gallery',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='productcategory_name',
        ),
        migrations.DeleteModel(
            name='tbl_brand',
        ),
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
        migrations.DeleteModel(
            name='tbl_product',
        ),
    ]
