# Generated by Django 5.0.2 on 2024-03-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0044_tbl_batterybrand_tbl_inverterbrand_tbl_panelbrand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_product',
            name='batterybrand_name',
        ),
        migrations.RemoveField(
            model_name='tbl_gallery',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='tbl_gallery',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='inverterbrand_name',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='panelbrand_name',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='productcategory_name',
        ),
        migrations.DeleteModel(
            name='tbl_batterybrand',
        ),
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
        migrations.DeleteModel(
            name='tbl_inverterbrand',
        ),
        migrations.DeleteModel(
            name='tbl_panelbrand',
        ),
        migrations.DeleteModel(
            name='tbl_product',
        ),
        migrations.DeleteModel(
            name='tbl_productcategory',
        ),
    ]
