# Generated by Django 5.0.2 on 2024-03-25 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0045_remove_tbl_product_batterybrand_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_batterybrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batterybrand_name', models.CharField(max_length=50)),
                ('battery_rate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_inverterbrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inverterbrand_name', models.CharField(max_length=50)),
                ('inverter_rate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_panelbrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panelbrand_name', models.CharField(max_length=50)),
                ('panel_rate', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_productcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productcategory_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.CharField(max_length=50)),
                ('product_desc', models.CharField(max_length=50)),
                ('product_image', models.FileField(upload_to='Assets/UserImage/')),
                ('batterybrand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_batterybrand')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('inverterbrand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_inverterbrand')),
                ('panelbrand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_panelbrand')),
                ('productcategory_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.CharField(max_length=50)),
                ('product_photo', models.FileField(upload_to='Assets/productphoto/')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subcategory')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_product')),
            ],
        ),
    ]
