# Generated by Django 5.0.2 on 2024-03-26 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0046_tbl_batterybrand_tbl_inverterbrand_tbl_panelbrand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=50)),
                ('package_description', models.CharField(max_length=50)),
                ('package_amount', models.CharField(max_length=50)),
                ('power', models.CharField(max_length=50)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_batterybrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_inverterbrand')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_panelbrand')),
            ],
        ),
    ]
