# Generated by Django 5.0.2 on 2024-03-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0051_tbl_package'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_package',
        ),
    ]
