# Generated by Django 5.0.2 on 2024-04-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0053_tbl_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_syllabus',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='tbl_emp',
            name='dept_name',
        ),
        migrations.RemoveField(
            model_name='tbl_emp',
            name='desg_name',
        ),
        migrations.RemoveField(
            model_name='tbl_gallery',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='tbl_gallery',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='batterybrand_id',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='inverterbrand_id',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='panelbrand_id',
        ),
        migrations.RemoveField(
            model_name='tbl_product',
            name='productcategory_name',
        ),
        migrations.RemoveField(
            model_name='tbl_syllabus',
            name='semester_name',
        ),
        migrations.RemoveField(
            model_name='tbl_subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tbl_syllabus',
            name='subject_name',
        ),
        migrations.DeleteModel(
            name='tbl_course',
        ),
        migrations.DeleteModel(
            name='tbl_dept',
        ),
        migrations.DeleteModel(
            name='tbl_desg',
        ),
        migrations.DeleteModel(
            name='tbl_emp',
        ),
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
        migrations.DeleteModel(
            name='tbl_product',
        ),
        migrations.DeleteModel(
            name='tbl_productcategory',
        ),
        migrations.DeleteModel(
            name='tbl_semester',
        ),
        migrations.DeleteModel(
            name='tbl_subcategory',
        ),
        migrations.DeleteModel(
            name='tbl_subject',
        ),
        migrations.DeleteModel(
            name='tbl_syllabus',
        ),
    ]
