# Generated by Django 5.0.2 on 2024-04-03 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0054_remove_tbl_syllabus_course_name_and_more'),
        ('Guest', '0048_remove_tbl_packageinterest_package_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_package',
        ),
    ]
