# Generated by Django 5.0.2 on 2024-04-03 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0056_tbl_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_quantity', models.CharField(max_length=50)),
                ('stock_date', models.DateField(auto_now_add=True)),
                ('package_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_package')),
            ],
        ),
    ]
