# Generated by Django 5.0.2 on 2024-04-04 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0057_tbl_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_stock',
        ),
    ]
