# Generated by Django 5.0.2 on 2024-04-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0061_tbl_package_tbl_stock'),
        ('Guest', '0052_remove_tbl_packageinterest_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_stock',
            name='package',
        ),
        migrations.DeleteModel(
            name='tbl_package',
        ),
        migrations.DeleteModel(
            name='tbl_stock',
        ),
    ]
