# Generated by Django 5.0.2 on 2024-04-20 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0063_tbl_package_tbl_stock'),
        ('Guest', '0085_remove_tbl_crassignorder_customisedrequests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_stock',
            name='package',
        ),
        migrations.DeleteModel(
            name='tbl_package',
        ),
        migrations.DeleteModel(
            name='tbl_stock',
        ),
    ]
