# Generated by Django 5.0.2 on 2024-02-20 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_newuser',
        ),
    ]
