# Generated by Django 5.0.2 on 2024-02-21 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_newuser',
        ),
    ]
