# Generated by Django 5.0.2 on 2024-03-05 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_sp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_sp',
        ),
    ]
