# Generated by Django 5.0.2 on 2024-03-05 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0033_tbl_product_tbl_gallery'),
        ('Guest', '0009_delete_tbl_sp'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_sp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_name', models.CharField(max_length=50)),
                ('sp_gender', models.CharField(max_length=50)),
                ('sp_contact', models.CharField(max_length=50)),
                ('sp_email', models.CharField(max_length=50)),
                ('sp_password', models.CharField(max_length=50)),
                ('sp_photo', models.FileField(upload_to='Assets/UserPhoto/')),
                ('sp_proof', models.FileField(upload_to='Assets/UserProof/')),
                ('sp_qualification', models.CharField(max_length=50)),
                ('sp_status', models.IntegerField(default='0')),
                ('place_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
