# Generated by Django 5.0.2 on 2024-03-25 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_tbl_complaint_tbl_proposal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_proposal',
        ),
    ]
