# Generated by Django 5.0.2 on 2024-03-25 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0046_tbl_batterybrand_tbl_inverterbrand_tbl_panelbrand_and_more'),
        ('Guest', '0013_tbl_proposal_tbl_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_proposal',
            name='batterybrand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_batterybrand'),
        ),
        migrations.AddField(
            model_name='tbl_proposal',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category'),
        ),
        migrations.AddField(
            model_name='tbl_proposal',
            name='inverterbrand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_inverterbrand'),
        ),
        migrations.AddField(
            model_name='tbl_proposal',
            name='panelbrand_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_panelbrand'),
        ),
        migrations.AlterField(
            model_name='tbl_proposal',
            name='proposal_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tbl_proposal',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser'),
        ),
    ]
