# Generated by Django 5.0.2 on 2024-03-26 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0046_tbl_batterybrand_tbl_inverterbrand_tbl_panelbrand_and_more'),
        ('Guest', '0015_remove_tbl_quotation_proposal_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_usage', models.CharField(max_length=500)),
                ('proposal_desc', models.CharField(max_length=50)),
                ('proposal_date', models.DateField(auto_now_add=True)),
                ('proposal_status', models.IntegerField(default='0')),
                ('batterybrand_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_batterybrand')),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('inverterbrand_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_inverterbrand')),
                ('panelbrand_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_panelbrand')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_power', models.CharField(max_length=50)),
                ('acc_rate', models.CharField(max_length=50)),
                ('quotation_total', models.CharField(max_length=50)),
                ('quotation_status', models.IntegerField(default='0')),
                ('quotation_date', models.DateField(auto_now_add=True)),
                ('battery_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_batterybrand')),
                ('inverter_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_inverterbrand')),
                ('panel_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_panelbrand')),
                ('proposal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_proposal')),
            ],
        ),
    ]
