# Generated by Django 5.0.2 on 2024-03-26 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0016_tbl_proposal_tbl_quotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_quotation',
            name='proposal_id',
        ),
        migrations.RemoveField(
            model_name='tbl_quotation',
            name='battery_rate',
        ),
        migrations.RemoveField(
            model_name='tbl_quotation',
            name='inverter_rate',
        ),
        migrations.RemoveField(
            model_name='tbl_quotation',
            name='panel_rate',
        ),
        migrations.DeleteModel(
            name='tbl_proposal',
        ),
        migrations.DeleteModel(
            name='tbl_quotation',
        ),
    ]
