# Generated by Django 5.0.2 on 2024-03-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0018_tbl_proposal_tbl_quotation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_quotation',
        ),
    ]
