# Generated by Django 5.0.2 on 2024-03-26 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0046_tbl_batterybrand_tbl_inverterbrand_tbl_panelbrand_and_more'),
        ('Guest', '0019_delete_tbl_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_power', models.CharField(max_length=50)),
                ('acc_rate', models.CharField(max_length=50)),
                ('quotation_total', models.CharField(max_length=50)),
                ('quotation_status', models.IntegerField(default='0')),
                ('quotation_date', models.DateField(auto_now_add=True)),
                ('batterybrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_batterybrand')),
                ('inverterbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_inverterbrand')),
                ('panelbrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_panelbrand')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_proposal')),
            ],
        ),
    ]
