# Generated by Django 5.0.2 on 2024-03-27 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0026_tbl_quotation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_quotation',
        ),
    ]
