# Generated by Django 5.0.2 on 2024-03-27 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0053_tbl_package'),
        ('Guest', '0028_tbl_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_packageinterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageinterest_date', models.DateField(auto_now_add=True)),
                ('packageinterest_msg', models.CharField(max_length=50)),
                ('packageinterest_status', models.IntegerField(default='0')),
                ('packageinterest_reply', models.CharField(max_length=500)),
                ('packageinterest_replydate', models.DateField(null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_package')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser')),
            ],
        ),
    ]
