# Generated by Django 5.0.2 on 2024-03-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0031_tbl_packageinterest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_packageinterest',
        ),
    ]
