# Generated by Django 5.0.2 on 2024-04-01 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0035_tbl_packageinterest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_packageinterest',
        ),
    ]
