# Generated by Django 5.0.2 on 2024-04-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0037_tbl_packageinterest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_quotation',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='tbl_quotation',
            name='batterybrand',
        ),
        migrations.RemoveField(
            model_name='tbl_quotation',
            name='inverterbrand',
        ),
        migrations.RemoveField(
            model_name='tbl_quotation',
            name='panelbrand',
        ),
        migrations.RemoveField(
            model_name='tbl_quotation',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_proposal',
        ),
        migrations.DeleteModel(
            name='tbl_quotation',
        ),
    ]
