# Generated by Django 5.0.2 on 2024-04-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0038_remove_tbl_quotation_proposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_packageinterest',
            name='packageinterest_pstatus',
            field=models.IntegerField(default='0'),
        ),
    ]
