# Generated by Django 5.0.2 on 2024-04-03 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0054_remove_tbl_syllabus_course_name_and_more'),
        ('Guest', '0039_tbl_packageinterest_packageinterest_pstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assignorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('assign_message', models.CharField(max_length=50)),
                ('assign_status', models.IntegerField(default='0')),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_batterybrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_inverterbrand')),
                ('packageinterest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_packageinterest')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_panelbrand')),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_sp')),
            ],
        ),
    ]
