# Generated by Django 5.0.2 on 2024-04-03 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0042_tbl_assignorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_assignorder',
        ),
    ]
