# Generated by Django 5.0.2 on 2024-04-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0046_tbl_assignorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_assignorder',
            name='category',
        ),
    ]
