# Generated by Django 5.0.2 on 2024-04-04 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0063_tbl_package_tbl_stock'),
        ('Guest', '0052_remove_tbl_packageinterest_package_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_packageinterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageinterest_date', models.DateField(auto_now_add=True)),
                ('packageinterest_msg', models.CharField(max_length=50)),
                ('packageinterest_status', models.IntegerField(default='0')),
                ('packageinterest_pstatus', models.IntegerField(default='0')),
                ('packageinterest_reply', models.CharField(max_length=500)),
                ('packageinterest_replydate', models.DateField(null=True)),
                ('quote_file', models.FileField(upload_to='Assets/Quotation/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_package')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_assignorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('assign_message', models.CharField(max_length=50)),
                ('assign_status', models.IntegerField(default='0')),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_sp')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser')),
                ('packageinterest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_packageinterest')),
            ],
        ),
    ]
