# Generated by Django 5.0.2 on 2024-04-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0053_tbl_packageinterest_tbl_assignorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
