# Generated by Django 5.0.2 on 2024-04-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0055_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
