# Generated by Django 5.0.2 on 2024-04-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0068_tbl_customisedrequests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_customisedrequests',
        ),
    ]
