# Generated by Django 5.0.2 on 2024-04-09 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0076_tbl_customisedrequests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_assignorder',
        ),
    ]
