# Generated by Django 5.0.2 on 2024-04-09 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0077_delete_tbl_assignorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_customisedrequests',
        ),
    ]
