# Generated by Django 5.0.2 on 2024-04-09 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0079_tbl_customisedrequests_tbl_assignorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_assignorder',
        ),
    ]
