# Generated by Django 5.0.2 on 2024-04-09 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0080_delete_tbl_assignorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assignorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('assign_message', models.CharField(max_length=50)),
                ('assign_status', models.IntegerField(default='0')),
                ('packageinterest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_packageinterest')),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_sp')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_crassignorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('assign_message', models.CharField(max_length=50)),
                ('assign_status', models.IntegerField(default='0')),
                ('customisedrequests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_customisedrequests')),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_sp')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser')),
            ],
        ),
    ]
