# Generated by Django 5.0.2 on 2024-04-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0081_tbl_assignorder_tbl_crassignorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_crassignorder',
        ),
    ]
