# Generated by Django 5.0.2 on 2024-04-20 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0084_tbl_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_crassignorder',
            name='customisedrequests',
        ),
        migrations.RemoveField(
            model_name='tbl_crassignorder',
            name='sp',
        ),
        migrations.RemoveField(
            model_name='tbl_crassignorder',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_customisedrequests',
            name='battery',
        ),
        migrations.RemoveField(
            model_name='tbl_customisedrequests',
            name='category',
        ),
        migrations.RemoveField(
            model_name='tbl_customisedrequests',
            name='inverter',
        ),
        migrations.RemoveField(
            model_name='tbl_customisedrequests',
            name='panel',
        ),
        migrations.RemoveField(
            model_name='tbl_customisedrequests',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_packageinterest',
            name='package',
        ),
        migrations.RemoveField(
            model_name='tbl_packageinterest',
            name='user',
        ),
        migrations.DeleteModel(
            name='tbl_assignorder',
        ),
        migrations.DeleteModel(
            name='tbl_crassignorder',
        ),
        migrations.DeleteModel(
            name='tbl_customisedrequests',
        ),
        migrations.DeleteModel(
            name='tbl_feedback',
        ),
        migrations.DeleteModel(
            name='tbl_packageinterest',
        ),
    ]
