# Generated by Django 5.0.2 on 2024-04-20 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0067_tbl_package'),
        ('Guest', '0087_remove_tbl_crassignorder_customisedrequests_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_customisedrequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('system', models.CharField(max_length=50)),
                ('cr_status', models.IntegerField(default='0')),
                ('customisedrequests_date', models.DateField(auto_now_add=True)),
                ('customisedrequests_reply', models.CharField(max_length=500)),
                ('customisedrequests_replydate', models.DateField(null=True)),
                ('cramount', models.CharField(max_length=50)),
                ('customisedrequests_pstatus', models.IntegerField(default='0')),
                ('customisedrequests_msg', models.CharField(max_length=50)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_batterybrand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_category')),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_inverterbrand')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_panelbrand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_crassignorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crassign_date', models.DateField(auto_now_add=True)),
                ('crassign_message', models.CharField(max_length=50)),
                ('crassign_status', models.IntegerField(default='0')),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_sp')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser')),
                ('customisedrequests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_customisedrequests')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_subject', models.CharField(max_length=500)),
                ('feedback_details', models.CharField(max_length=500)),
                ('feedback_postdate', models.DateField(auto_now_add=True)),
                ('feedback_status', models.IntegerField(default='0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_packageinterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageinterest_date', models.DateField(auto_now_add=True)),
                ('packageinterest_msg', models.CharField(max_length=50)),
                ('packageinterest_status', models.IntegerField(default='0')),
                ('packageinterest_pstatus', models.IntegerField(default='0')),
                ('packageinterest_reply', models.CharField(max_length=500)),
                ('packageinterest_replydate', models.DateField(null=True)),
                ('quote_file', models.FileField(upload_to='Assets/Quotation/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_package')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_assignorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('assign_message', models.CharField(max_length=50)),
                ('assign_status', models.IntegerField(default='0')),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_sp')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_newuser')),
                ('packageinterest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_packageinterest')),
            ],
        ),
    ]
